In [3]:
import pandas as pd

df = pd.read_csv("data/Sample - Superstore.csv", encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# Dataset Problem:
- Data chưa được chuẩn hoá

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [5]:
# chuẩn hoá tên các cột
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

In [7]:
df.duplicated().sum()

np.int64(0)

- No nulls
- No missing values
- No duplicated values

In [8]:
# chuyển kiểu dữ liệu ngày tháng
df["order_date"] = pd.to_datetime(df["order_date"])
df["ship_date"] = pd.to_datetime(df["ship_date"])

df[["order_date", "ship_date"]].head()

  order_date  ship_date
0 2016-11-08 2016-11-11
1 2016-11-08 2016-11-11
2 2016-06-12 2016-06-16
3 2015-10-11 2015-10-18
4 2015-10-11 2015-10-18

In [9]:
df.head(10)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

Bộ dữ liệu khá đặc biệt, nếu để y nguyên thì chúng chưa có thuộc tính khoá chính "Toàn bọ khoá chính"
It means:
- Nếu khoá chính chỉ có 1 cột thôi thì ok auto đạt điều kiện
- Nhưng nếu khoá chính được xác định từ nhiều cột thì chúng ta phải kiểm tra sự phụ thuộc.
- Trong bộ dữ liệu này nếu nói khoá chính là Order ID thì không đúng VÌ 1 order có thể chứa nhiều sản phẩm. Nếu nói Product ID là khoá chính cũng không phải vì 1 sản phẩm xuất hiện trong nhiều đơn hàng.
- ...

In [24]:
df.groupby("order_id").size().sort_values(ascending=False).head(10)

order_id
CA-2017-100111    14
CA-2017-157987    12
US-2016-108504    11
CA-2016-165330    11
CA-2016-105732    10
CA-2015-131338    10
US-2015-126977    10
CA-2015-158421     9
CA-2016-145177     9
US-2015-163433     9
dtype: int64

1 mã đơn hàng xuất hiện nhiều lần trong dataset (có nghĩa là 1 đơn hàng k chỉ mua 1 sản phẩm)

In [ ]:
'''
 tạo khoá chính tạm thời bằng cách ghép các cột với nhau. 
 Ở đây, 1 đơn hàng = nhiều sản phẩm và ngược lại
 Thực tế nếu nói row_id là khoá chính thì cũng không sai, NHƯNG:
    - nếu nói đơn hàng CA-2016-152156 = dòng thứ 2, nhưng nếu hỏi dòng 2000 là gì thì k xác định được
    - Với business understanding thì order và order item khác nhau
=> kết hợp 2 cột này với nhau ổn hơn ^^
'''

df["order_item_id"] = df["order_id"].astype(str) + "_" + df["row_id"].astype(str)

df[["order_item_id", "order_id", "product_id"]].head()

      order_item_id        order_id       product_id
0  CA-2016-152156_1  CA-2016-152156  FUR-BO-10001798
1  CA-2016-152156_2  CA-2016-152156  FUR-CH-10000454
2  CA-2016-138688_3  CA-2016-138688  OFF-LA-10000240
3  US-2015-108966_4  US-2015-108966  FUR-TA-10000577
4  US-2015-108966_5  US-2015-108966  OFF-ST-10000760

In [11]:
# tạo bảng Customers

customers = df[[
    "customer_id",
    "customer_name",
    "segment"
]].drop_duplicates()

customers.head()

   customer_id    customer_name    segment
0     CG-12520      Claire Gute   Consumer
2     DV-13045  Darrin Van Huff  Corporate
3     SO-20335   Sean O'Donnell   Consumer
5     BH-11710  Brosina Hoffman   Consumer
12    AA-10480     Andrew Allen   Consumer

In [12]:
# tạo bảng products

products = df[[
    "product_id",
    "category",
    "sub_category",
    "product_name"
]].drop_duplicates()

products.head()

,product_id,category,sub_category,product_name
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
1,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...
3,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table
4,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System

In [13]:
products.groupby("product_id").size().sort_values(ascending=False).head()

product_id
TEC-PH-10001795    2
OFF-BI-10002026    2
OFF-PA-10003022    2
OFF-AR-10001149    2
OFF-PA-10001970    2
dtype: int64

In [14]:
products[
    products["product_id"] == "TEC-PH-10001795"
]

,product_id,category,sub_category,product_name
806,TEC-PH-10001795,Technology,Phones,ClearOne CHATAttach 160 - speaker phone
5513,TEC-PH-10001795,Technology,Phones,RCA H5401RE1 DECT 6.0 4-Line Cordless Handset ...

In [15]:
# tạo bảng locations
locations = df[[
    "country",
    "city",
    "state",
    "postal_code",
    "region"
]].drop_duplicates().reset_index(drop=True)

locations["location_id"] = range(1, len(locations) + 1)

locations = locations[[
    "location_id",
    "country",
    "city",
    "state",
    "postal_code",
    "region"
]]

locations.head()

,location_id,country,city,state,postal_code,region
0,1,United States,Henderson,Kentucky,42420,South
1,2,United States,Los Angeles,California,90036,West
2,3,United States,Fort Lauderdale,Florida,33311,South
3,4,United States,Los Angeles,California,90032,West
4,5,United States,Concord,North Carolina,28027,South

In [16]:
df = df.merge(
    locations,
    on=["country", "city", "state", "postal_code", "region"],
    how="left"
)

df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,product_id,category,sub_category,product_name,sales,quantity,discount,profit,order_item_id,location_id
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,CA-2016-152156_1,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,CA-2016-152156_2,1
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,CA-2016-138688_3,2
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,US-2015-108966_4,3
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,US-2015-108966_5,3

In [17]:
# tạo bảng orders
orders = df[[
    "order_id",
    "order_date",
    "ship_date",
    "ship_mode",
    "customer_id",
    "location_id"
]].drop_duplicates()

orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,location_id
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,1
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,2
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,3
5,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,4
12,CA-2017-114412,2017-04-15,2017-04-20,Standard Class,AA-10480,5

In [18]:
orders["order_id"].is_unique

True

In [19]:
# tạo bảng order_item
order_items = df[[
    "order_item_id",
    "order_id",
    "product_id",
    "sales",
    "quantity",
    "discount",
    "profit"
]]

order_items.head()

,order_item_id,order_id,product_id,sales,quantity,discount,profit
0,CA-2016-152156_1,CA-2016-152156,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,CA-2016-152156_2,CA-2016-152156,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,CA-2016-138688_3,CA-2016-138688,OFF-LA-10000240,14.6200,2,0.00,6.8714
3,US-2015-108966_4,US-2015-108966,FUR-TA-10000577,957.5775,5,0.45,-383.0310
4,US-2015-108966_5,US-2015-108966,OFF-ST-10000760,22.3680,2,0.20,2.5164

In [20]:
order_items["order_item_id"].is_unique

True

In [21]:
print("customers:", customers.shape)
print("products:", products.shape)
print("locations:", locations.shape)
print("orders:", orders.shape)
print("order_items:", order_items.shape)

customers: (793, 3)
products: (1894, 4)
locations: (632, 6)
orders: (5009, 6)
order_items: (9994, 7)

In [ ]:
# xuất thành file CSV:

customers.to_csv("data/customers.csv", index=False)
products.to_csv("data/products.csv", index=False)
locations.to_csv("data/locations.csv", index=False)
orders.to_csv("data/orders.csv", index=False)
order_items.to_csv("data/order_items.csv", index=False)